# Generated by Django 5.1.5 on 2025-02-20 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curricular', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
    ]
