# Generated by Django 5.1.5 on 2025-02-20 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricular', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='course',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='curricular.course'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='hour',
            field=models.IntegerField(blank=True, choices=[(1, '9-10'), (2, '10-11'), (3, '11-12'), (4, '12-1'), (5, '2-3'), (6, '3-4'), (7, '4-5')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='marked_attendance', to='curricular.teacher'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='curricular.student'),
        ),
    ]
