# Generated by Django 5.1.5 on 2025-02-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricular', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
