# Generated by Django 5.1.5 on 2025-02-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricular', '0003_assignmentsubmission_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmarks',
            name='marks_obtained',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
