# Generated by Django 5.1.5 on 2025-02-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricular', '0004_alter_studentmarks_marks_obtained'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('Mid Semester', 'Mid Semester'), ('End Semester', 'End Semester'), ('Lab', 'Lab'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
