# Generated by Django 5.1.5 on 2025-03-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricular', '0005_alter_assessment_assessment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='semester',
        ),
        migrations.AddField(
            model_name='assessment',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6')], default=1),
        ),
    ]
