# Generated by Django 5.1.5 on 2025-03-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricular', '0007_assignment_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='assessment_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
