# Generated by Django 5.0.6 on 2025-03-08 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curricular", "0009_alter_assessment_assessment_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="class_teacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="class_courses",
                to="curricular.teacher",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="year",
            field=models.IntegerField(default=2024),
            preserve_default=False,
        ),
    ]
