# Generated by Django 5.1.5 on 2025-03-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricular', '0010_course_class_teacher_course_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='career_objective',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='hard_skills',
            field=models.TextField(blank=True, help_text='Comma-separated skills', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='soft_skills',
            field=models.TextField(blank=True, help_text='Comma-separated skills', null=True),
        ),
    ]
