# Generated by Django 5.1.5 on 2025-03-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricular', '0011_department_hod'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_semesters',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.IntegerField(default=6),
        ),
    ]
