# Generated by Django 5.1.5 on 2025-03-09 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricular', '0012_course_total_semesters_alter_student_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='curricular.subject'),
            preserve_default=False,
        ),
    ]
