# Generated by Django 5.1.5 on 2025-03-09 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curricular', '0013_attendance_subject'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date', 'hour', 'subject')},
        ),
    ]
