# Generated by Django 5.1.5 on 2025-03-11 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricular', '0015_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='alumni', to='curricular.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='curricular.department'),
            preserve_default=False,
        ),
    ]
