# Generated by Django 5.1.5 on 2025-03-14 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curricular', '0010_course_class_teacher_course_year'),
        ('curricular', '0016_alumni_department_student_department'),
    ]

    operations = [
    ]
