# Generated by Django 5.1.5 on 2025-02-13 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClubMembers',
        ),
    ]
