# Generated by Django 5.1.5 on 2025-02-13 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_clubmembers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_club', models.CharField(max_length=255)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('club', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='club_members', to='api.club')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to='api.student')),
            ],
            options={
                'unique_together': {('student', 'club')},
            },
        ),
    ]
