# Generated by Django 5.1.5 on 2025-02-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_assignment_is_completed_alter_assignment_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='due_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
