# Generated by Django 5.0.6 on 2025-02-13 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_subject_attendance_assignment_studentmarks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="leader",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="club_leader_extra",
                to="api.student",
            ),
        ),
        migrations.AlterField(
            model_name="clubmembers",
            name="club",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members_extra",
                to="api.club",
            ),
        ),
        migrations.AlterField(
            model_name="clubmembers",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="club_members_extra",
                to="api.student",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="attendees",
            field=models.ManyToManyField(
                blank=True, related_name="events_attending_extra", to="api.student"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events_extra",
                to="api.club",
            ),
        ),
    ]
