# Generated by Django 5.1.5 on 2025-02-17 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_student_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
        migrations.AlterField(
            model_name='clubmembers',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to='api.student'),
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('participation_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_in_event', models.CharField(blank=True, max_length=50, null=True)),
                ('achievement', models.CharField(blank=True, max_length=255, null=True)),
                ('club_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to='api.clubmembers')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='api.event')),
            ],
            options={
                'unique_together': {('club_member', 'event')},
            },
        ),
    ]
