# Generated by Django 5.0.6 on 2025-02-14 09:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_club_leader_alter_clubmembers_club_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clubmembers",
            options={
                "verbose_name": "Club Member",
                "verbose_name_plural": "Club Members",
            },
        ),
        migrations.RenameField(
            model_name="event",
            old_name="name",
            new_name="event_name",
        ),
        migrations.RemoveField(
            model_name="event",
            name="date",
        ),
        migrations.AddField(
            model_name="club",
            name="club_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="event_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="club",
            name="faculty_incharge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clubs_incharge",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="leader",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="club_leader",
                to="api.student",
            ),
        ),
        migrations.AlterField(
            model_name="clubmembers",
            name="club",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="api.club",
            ),
        ),
        migrations.AlterField(
            model_name="clubmembers",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="club_members",
                to="api.student",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="attendees",
            field=models.ManyToManyField(
                blank=True, related_name="events_attending", to="api.student"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="api.club",
            ),
        ),
    ]
