# Generated by Django 5.1.5 on 2025-02-16 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_assignment_is_completed'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentmarks',
            unique_together={('assessment', 'student')},
        ),
    ]
