# Generated by Django 5.0.6 on 2025-02-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_clubmembers_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="year_of_study",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
