# Generated by Django 5.1.5 on 2025-02-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_teacher_subject_teacher_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='api.course'),
        ),
    ]
