# Generated by Django 5.1.5 on 2025-02-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_teacher_subject_remove_teacher_course_teacher_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='course',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='api.course'),
        ),
    ]
