# Generated by Django 5.1.5 on 2025-02-17 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_teacher_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='course',
            new_name='courses',
        ),
    ]
