# Generated by Django 5.1.5 on 2025-02-17 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_course_teacher_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='courses',
            new_name='course',
        ),
    ]
