# Generated by Django 5.0.6 on 2025-03-09 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cocurricular", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ClassTeacher",
        ),
    ]
