# Generated by Django 5.0.6 on 2025-03-09 06:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cocurricular", "0002_delete_classteacher"),
        ("curricular", "0010_course_class_teacher_course_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="internship",
            name="approved_by",
        ),
        migrations.AddField(
            model_name="internship",
            name="assigned_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_internships",
                to="curricular.teacher",
            ),
        ),
        migrations.AddField(
            model_name="internship",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="internship",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
