# Generated by Django 5.0.6 on 2025-03-09 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cocurricular", "0003_remove_internship_approved_by_and_more"),
        ("curricular", "0010_course_class_teacher_course_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internship",
            name="assigned_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teacher_internships",
                to="curricular.teacher",
            ),
        ),
    ]
