# Generated by Django 5.1.5 on 2025-02-21 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricular', '0004_alter_studentmarks_marks_obtained'),
        ('noti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noti',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif', to='curricular.course'),
        ),
    ]
