# Generated by Django 5.1.5 on 2025-03-11 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
        ('curricular', '0015_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='alumni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curricular.alumni'),
        ),
        migrations.DeleteModel(
            name='Alumni',
        ),
    ]
