# Generated by Django 5.1.5 on 2025-03-11 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_alter_donation_alumni_delete_alumni'),
        ('curricular', '0016_alumni_department_student_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnievent',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='alumni_events', to='curricular.department'),
            preserve_default=False,
        ),
    ]
