# Generated by Django 5.1.5 on 2025-02-18 19:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curricular', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_id', models.AutoField(primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=255, unique=True)),
                ('club_category', models.CharField(max_length=255)),
                ('club_description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('faculty_incharge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs_incharge', to=settings.AUTH_USER_MODEL)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curricular.student')),
            ],
        ),
        migrations.CreateModel(
            name='ClubMembers',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_in_club', models.CharField(choices=[('Leader', 'Leader'), ('Member', 'Member')], default='Member', max_length=10)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='extracurricular.club')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to='curricular.student')),
            ],
            options={
                'verbose_name': 'Club Member',
                'verbose_name_plural': 'Club Members',
                'unique_together': {('student', 'club')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('event_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='extracurricular.club')),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('participation_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_in_event', models.CharField(blank=True, max_length=50, null=True)),
                ('achievement', models.CharField(blank=True, max_length=255, null=True)),
                ('club_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to='extracurricular.clubmembers')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='extracurricular.event')),
            ],
            options={
                'unique_together': {('club_member', 'event')},
            },
        ),
    ]
