# Generated by Django 5.1.5 on 2025-02-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracurricular', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club_logo',
            field=models.ImageField(blank=True, null=True, upload_to='club_logos/'),
        ),
    ]
